// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwQIL2Tl2fTtuL99QXXXakXIde3UrnPAw',
    appId: '1:590998060276:web:ef4b548c2d5ed905c872a1',
    messagingSenderId: '590998060276',
    projectId: 'lf-survey-app-flutter',
    authDomain: 'lf-survey-app-flutter.firebaseapp.com',
    storageBucket: 'lf-survey-app-flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVGbQx512MJRhE_vPxjs80g9iWQY1QsUU',
    appId: '1:590998060276:android:152cc8eb43f21631c872a1',
    messagingSenderId: '590998060276',
    projectId: 'lf-survey-app-flutter',
    storageBucket: 'lf-survey-app-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU7LNMMMvXWGZJdxsoCaB4zkyXd7nO_pk',
    appId: '1:590998060276:ios:17a9277c1f5c690ac872a1',
    messagingSenderId: '590998060276',
    projectId: 'lf-survey-app-flutter',
    storageBucket: 'lf-survey-app-flutter.firebasestorage.app',
    iosBundleId: 'com.example.lfSurvey',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBU7LNMMMvXWGZJdxsoCaB4zkyXd7nO_pk',
    appId: '1:590998060276:ios:17a9277c1f5c690ac872a1',
    messagingSenderId: '590998060276',
    projectId: 'lf-survey-app-flutter',
    storageBucket: 'lf-survey-app-flutter.firebasestorage.app',
    iosBundleId: 'com.example.lfSurvey',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwQIL2Tl2fTtuL99QXXXakXIde3UrnPAw',
    appId: '1:590998060276:web:5d7ff61530e05575c872a1',
    messagingSenderId: '590998060276',
    projectId: 'lf-survey-app-flutter',
    authDomain: 'lf-survey-app-flutter.firebaseapp.com',
    storageBucket: 'lf-survey-app-flutter.firebasestorage.app',
  );
}
